### ISSUE TITLE
Nice...

### ISSUE THREAD

**Issue by stonea** [adamlabadorf/bobogoestoharvard#1]
https://github.com/adamlabadorf/bobogoestoharvard/blob/d166b728b18beb120ffc37fe6c2e7c81f4706e27/scripts/boboButt.js#L6

I feel like this string needs to be factored out into a message catalog. We don’t want to have to track all the random text down when it comes time to translate this for the Japanese version.

**Comment by adamlabadorf** [comment]
Bobo supports robust internationalization standards.

**Comment by stonea** [comment]
Solid argument. Closing the issue.
